### ISSUE TITLE
already closed window

### ISSUE THREAD

**Issue by tonydero** [apexatoll/cliptic#1]
When installing via `gem install cliptic` resulting in the output

    Fetching cliptic-0.1.0.gem
    Fetching sqlite3-1.4.2.gem
    Fetching curses-1.4.2.gem
    Fetching curb-0.9.11.gem
    WARNING:  You don't have /home/<user>/.local/share/gem/ruby/3.0.0/bin in your PATH,
              gem executables will not run.
    Building native extensions. This could take a while...
    Successfully installed sqlite3-1.4.2
    Building native extensions. This could take a while...
    Successfully installed curses-1.4.2
    Building native extensions. This could take a while...
    Successfully installed curb-0.9.11
    Successfully installed cliptic-0.1.0
    4 gems installed

every time I try to run it I only get the result `already closed window`? 

I've run it both directly from the `~/.local/share/gem/ruby/3.0.0/bin` directory and also via a symlink to a directory in my path.

I'm on Arch Linux with `gem` version `3.2.21`.

Thoughts?

**Comment by apexatoll** [comment]
This is an error that usually comes about if there is not enough screen space for the program to run - there is a built in resizer but I'm guessing that if there it is not enough space for this then you will get this error. Have you tried resizing the screen ± zooming out?

**Comment by tonydero** [comment]
I thought it might be related to that, but when I've gone to as big as 79 lines x 349 cols it still gives the message. I would assume that's big enough?

Oh, also have tried in both Fish and Bash with the same result.

**Comment by apexatoll** [comment]
That's definitely large enough - what terminal are you trying on? You can comment out lines 7-9 in lib/cliptic/terminal.rb for a more detailed error message

**Comment by fedexcain** [comment]
Terminal is alacritty. Shell is zsh. I normally use tmux, but the error appears with and without a tmux session.
```
$CLIPTIC_DIR/gems/cliptic-0.1.0/lib/cliptic/windows.rb:13:in 'keypad': already closed window (RuntimeError)
        from $CLIPTIC_DIR/gems/cliptic-0.1.0/lib/cliptic/windows.rb:13:in 'initialize'
        from $CLIPTIC_DIR/gems/cliptic-0.1.0/lib/cliptic/windows.rb:119:in 'initialize'
        from $CLIPTIC_DIR/gems/cliptic-0.1.0/lib/cliptic/interface.rb:36:in 'initialize'
        from $CLIPTIC_DIR/gems/cliptic-0.1.0/lib/cliptic/interface.rb:52:in 'new'
        from $CLIPTIC_DIR/gems/cliptic-0.1.0/lib/cliptic/interface.rb:52:in 'initialize'
        from $CLIPTIC_DIR/gems/cliptic-0.1.0/lib/cliptic/interface.rb:168:in 'initialize'
        from $CLIPTIC_DIR/gems/cliptic-0.1.0/lib/cliptic/interface.rb:255:in 'initialize'
        from $CLIPTIC_DIR/gems/cliptic-0.1.0/lib/cliptic/config.rb:54:in 'new'
        from $CLIPTIC_DIR/gems/cliptic-0.1.0/lib/cliptic/config.rb:54:in 'gen_cfg_menu'
        from $CLIPTIC_DIR/gems/cliptic-0.1.0/lib/cliptic/config.rb:30:in 'set'
        from $CLIPTIC_DIR/gems/cliptic-0.1.0/lib/cliptic/terminal.rb:13:in 'setup'
        from $CLIPTIC_DIR/gems/cliptic-0.1.0/lib/cliptic/terminal.rb:18:in 'main_menu'
        from $CLIPTIC_DIR/gems/cliptic-0.1.0/lib/cliptic/terminal.rb:6:in 'run'
        from $CLIPTIC_DIR/gems/cliptic-0.1.0/bin/cliptic:5:in '<top (required)>'
        from $CLIPTIC_DIR/bin/cliptic:23:in 'load'
        from $CLIPTIC_DIR/bin/cliptic:23:in '<main>'
```

**Comment by apexatoll** [comment]
Ah this is a silly error - the config is tried to be loaded before the screen is set up. Should be fixed in latest version. Let me know

**Comment by fedexcain** [comment]
Yes, it's fixed :+1:

**Comment by apexatoll** [comment]
Perfect

**Comment by tonydero** [comment]
Also fixed for me, thanks!
