### ISSUE TITLE
undefined method `[]' for nil:NilClass

### ISSUE THREAD

**Issue by logix2** [apexatoll/cliptic#3]
When I try to run cliptic (installed using `gem install...`) I get this error: "undefined method `[]' for nil:NilClass"

I'm using ruby 2.7.2p137 on Ubuntu 21.04. Let me know if you need other details.

**Comment by apexatoll** [comment]
This is an error most likely due to your terminal size, there is a bug with the resize prompt screen that will be fixed in a patch in the next couple of days

Please try increasing your terminal size/zooming out

**Comment by logix2** [comment]
That was it, thanks!

**Comment by apexatoll** [comment]
This bug is now fixed in 0.1.2
