### ISSUE TITLE
Allow redrawing screen 

### ISSUE THREAD

**Issue by nulani38728** [apexatoll/cliptic#4]
If starting the program in a window large enough to draw the interface, but then resizing (or navigating away from the program using a tiled window/fullscreen toggle, such that the geometry changes to be smaller than cliptic's desired geometry) and returning again, the ncurses output becomes garbled during the temporary geometry change and is unable to update again. Would it be possible to allow the user to manually redraw the window via a keybinding? 

This is readily apparent on a tiling window manager due to the way the windows are resized on the fly.  
Note: this will not occur if you resize to a larger geometry, but once you resize to a smaller geometry such that the lines wrap, it will be permanently distorted.

Terminal emulator: urxvt
Window manager: i3

**Comment by apexatoll** [comment]
I did try to implement a resize screen within the main game interface similar to the menu interfaces, but I didnt manage to get this working. A manual redraw keybinding could work - I will look into it

**Comment by nulani38728** [comment]
I'm wondering if it would be possible to just truncate the lines to the width of the terminal when the window is too small, and then repaint it/allow the user to repaint it later--rather than allowing the lines to dynamically wrap.

About the main menu, it seems there are some conditions where it won't let you proceed even if the terminal is fullscreened. For example, if the point size and display resolution combination would exceed whatever upper bound cliptic expects. E.g., pt. size 32 in urxvt `.Xdefaults` on a 1440p display works, but on a 1080p display, will warn that the screen is too small, even if the only thing you have open is a terminal emulator. Of course, this will work if you put it back on a 1440p display.

It seems like some of this could be ameliorated by just left-justifying everything, since the centering can cause a lot of line wrapping issues. Alternatively, perhaps user-configurable size parameters or a noisy exit could help.

Relatedly, see #5.

I know curses can be annoying to tame. I'm trying to look at some examples of applications that work around these behaviors. I think [newsboat](https://github.com/newsboat/newsboat) might be a valid example; the view just gets truncated horizontally or vertically, instead of pushing content onto the next line.

**Comment by apexatoll** [comment]
Sorry I haven't got back to you on this - been very busy but will be able to take a look at your issues over the coming week. I'm not quite sure what you're asking here - cliptic needs a certain number of columns and rows to display the puzzle in full. If your font size is up/resolution changes then this will limit the number of columns/rows on your terminal screen. I'm not sure how left justifying everything will help but I agree that a manual redraw control would be useful so will look into it this week, as well as another issue you pointed out regarding the "non-quittable" resize screens

**Comment by apexatoll** [comment]
Implemented in 0.1.3 - apologies for the delay!

You can now use ^L to manually redraw the screen on terminal resize

**Comment by nulani38728** [comment]
Thank you for the fix!
