### ISSUE TITLE
Quit/hangup keys blocked on "screen too small" warning

### ISSUE THREAD

**Issue by nulani38728** [apexatoll/cliptic#5]
It's not possible to quit the program using `q`, `^C`, or `^D` when being served the "screen too small" warning, and must be forcibly terminated. The program expects to receive a quit signal only in "normal" mode. This means you can become softlocked if you open it in an environment where your combination of display settings doesn't support the expected display size. (See #4)

**Comment by apexatoll** [comment]
Implemented in 0.1.3 - resizer can be exited using 'q' or ^C
