### ISSUE TITLE
Support exporting puzzle? 

### ISSUE THREAD

**Issue by mixographer** [apexatoll/cliptic#7]
Thanks for this tool. I don't understand how Ruby works any more. I used to just run ruby and it worked, now There seem to be so many steps and versions, I can't do anything in Ruby. 

Anyway, I was wondering if this tool could support exporting the puzzles in a format compatible with other crossword tools as well?Like PUZ or PUZ(txt) or XD or JPZ? It would be neat if there was a list in the terminal of the puzzles you had cached in the database, and then you could export them in a common format.

**Comment by mixographer** [comment]
Also, can you explain how the puzzle URLs work? If I do something like this: 
https://data.puzzlexperts.com/puzzleapp-v3/data.php?psid={100000160}&date={2022-12-12} 

I get something like this: 
{"cells" :[{"x":0,"y":0,"meta":{"rendererID":"Default","data":""}}],"rows":1,"columns":1,"meta":{"rating":5}}

**Comment by apexatoll** [comment]
Unfortunately there are no plans to export to existing puzzle formats. The API is publicly exposed, but as the website they are hosted on does not support this functionality it is not the scope of this application to add this. 

That response is correct - part of cliptic's functionality was to reverse engineer this response and parse it into a useful, playable format

**Comment by mixographer** [comment]
I understand. thanks.
